### ISSUE TITLE
Camera Not Spawning

### ISSUE THREAD

**Issue by jenson222** [gingerphoenix10/ContentPOVs#6]
Hey! So, me and my friends downloaded a couple of mods. But, for some reason, it doesn't spawn the camera. Do you know why this could be?

**Comment by gingerphoenix10** [comment]
I've seen this issue mentioned a few times, but I haven't been able to recreate it for whatever reason.
I can only guess that it might be a load order bug? So you can try going to Content Warning on Steam > Properties > Workshop > Show Advanced Options > Find Best Load Order.
If you could also send your current installed mods and load order, that'd be nice, but no pressure :)

https://github.com/user-attachments/assets/0d8ad9b4-806b-4d2c-b8ad-bb1ce9050c18

**Comment by jenson222** [comment]
Yeah, sure here ya go. 
![image](https://github.com/user-attachments/assets/17d954f2-87bc-49c6-ac70-adc80dc1a135)
![image](https://github.com/user-attachments/assets/d798f74d-0e5f-48f7-88bc-69c6b82ae037)

Btw, how do you find the load order? Sorry i'm kinda new to modding stuff.

Thanks,

**Comment by jenson222** [comment]
I removed Charging Divebell, CaughtIn4K, Helldivers, and Better Lobby cuz it wasn't working but when I start it without them, the task says to "pick up the camera" when it's not there.

**Comment by gingerphoenix10** [comment]
Ahh, right. Forgot about the Thunderstore version.
Thunderstore handles load order automatically, so it's probably just a problem with mod itself. I'll try and update it when I get home :)

**Comment by jenson222** [comment]
oh alright! can you send a reply to this message when you finish the update? thanks.

**Comment by gingerphoenix10** [comment]
Should hopefully be fixed in v1.2.0. We'll see ¯\_(ツ)_/¯
https://thunderstore.io/c/content-warning/p/gingerphoenix10/ContentPOVs/ (May take a few minutes for the update to show up on r2modman / thunderstore mod manager)

**Comment by jenson222** [comment]
It's fixed, thank you so much for taking the time to fix it. Have a good day.

**Comment by gingerphoenix10** [comment]
Np! Thanks for reporting the issue! :)
Have a nice day!
